### ISSUE TITLE
double_cmdq_to_quit issue

### ISSUE THREAD

**Issue by gatspy** [raulchen/dotfiles#2]
double cmd+q can't quit chrome

`chrome version:` `62.0.3202.94`

**Comment by raulchen** [comment]
Hi @gatspy, it works well for me.
what language is your system? If you're using a language other than English and simplified Chinese, you'll need to add the equivalent word of "Quit"  in your language here https://github.com/raulchen/dotfiles/blob/master/hammerspoon/double_cmdq_to_quit.lua#L18.

**Comment by gatspy** [comment]
thanks for your reply!
using 'simplified Chinese'.
when double `cmd+q` push down, `confirm menu ` checked.
![jietu20171124-180545](https://user-images.githubusercontent.com/804446/33205536-43aef926-d142-11e7-8fad-9a121204b694.jpg)

**Comment by raulchen** [comment]
@gatspy the way this script works is to choose the first menu item whose name starts with "退出".
In this case, you can add the following line below this line (https://github.com/raulchen/dotfiles/blob/master/hammerspoon/double_cmdq_to_quit.lua#L8) to work around
`WHITELIST["com.google.chrome"] = "退出Google Chrome"`

Thanks for reporting this issue, I should make this script smarter.

**Comment by raulchen** [comment]
Actually, forget about the previous comment. 
I just changed the script to use HS's `quit` API. It should work stably for all Apps now, regardless system language. 
https://github.com/raulchen/dotfiles/blob/master/hammerspoon/double_cmdq_to_quit.lua
Please let me know if you still see any issue.

**Comment by gatspy** [comment]
thanks! thanks! thanks!
work fine!
