### ISSUE TITLE
Problem with smart_modifier_keys and Terminal

### ISSUE THREAD

**Issue by overvale** [raulchen/dotfiles#3]
I've been using `smart_modifier_keys` today and I noticed something that maybe it's a bug but maybe is worth mentioning.

I have the "Secure Keyboard Entry" setting enabled in Terminal, and after typing anything into Terminal `smart_modifier_keys breaks` -- typing `ls` and then `ctrl+a` both moves the cursor to the beginning of the line AND triggers `escape`. And it remains broken until you quit Terminal (sometimes until you relaunch Terminal, but don't type anything).

It's obscure, but I thought I'd mention it.

Also, I've been searching for an extensible way to do this will all modifier keys and this is by FAR the best hammerspoon solution I've seen. Well done. My version is [here](https://github.com/olivertaylor/dotfiles/blob/master/hammerspoon/smart_modifier_keys.lua).

**Comment by raulchen** [comment]
> typing ls and then ctrl+a both moves the cursor to the beginning of the line AND triggers escape. And it remains broken until you quit Terminal (sometimes until you relaunch Terminal, but don't type anything).

Hey @olivertaylor, I just tried this. "both moves the cursor to the beginning of the line AND triggers escape" happened for me. But `smart_modifier_keys` wasn't broken. By the way, I'm using vim-mode, so "triggering escape" would just change my command-line to visual mode. I'm not sure whether it's related. 

Thanks for mentioning this. I don't use Terminal.app and didn't know this issue.
